producer_main/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'MechRevTest.views.home', name='home'),
    # url(r'^MechRevTest/', include('MechRevTest.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/?', include(admin.site.urls)),

    url(r'^api/v1/', include('producer.urls', namespace='producer')),
    url(r'^touchstone/api/v1/', include('producer.urls', namespace='producer.touchstone')),
    url(r'^touchstone/', include('ui.urls', namespace='touchstone.ui')),
    url(r'^/?', include('ui.urls', namespace='ui')),
)

ui/urls.py
from django.conf.urls import patterns, url
from ui import views

urlpatterns = patterns('',
    url(r'^check/?$',
        views.check_credentials,
        name="check"),
    url(r'^dashboard/?$',
        views.dashboard,
        name="dashboard"),
    url(r'^logout/?$',
        views.logout_user,
        name="logout"),
    url(r'^privacy/?$',
        views.privacy,
        name="privacy"),
    url(r'^tos/?$',
        views.tos,
        name="tos"),
    url(r'',
        views.login_page,
        name="login"),
)

ui/views.py
from django.conf import settings
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponseRedirect, Http404

from dlkit.runtime.primitives import Type

from dysonx.dysonx import get_or_create_user_repo

from dlkit.records.registry import REPOSITORY_GENUS_TYPES

from utilities.general import log_error, activate_managers, get_session_data, extract_items


def check_credentials(request):
    username = request.POST['username']
    password = request.POST['password']
    redirect_url = request.POST['next']

    try:
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                if user.is_authenticated():
                    if not redirect_url or redirect_url == '':
                        redirect_url = '/dashboard/'
                    return HttpResponseRedirect(redirect_url)
                else:
                    raise AssertionError('Bad credentials provided.')
            else:
                raise AssertionError('Bad credentials provided.')
        else:
            raise AssertionError('Bad credentials provided.')
    except AssertionError as ex:
        return render_to_response('ui/login.html',
                                  {'state': ex.args[0]},
                                  RequestContext(request))
    except Exception as ex:
        msg = log_error('ui.views.check_credentials()', ex)
        return Http404(msg)

@login_required()
@user_passes_test(lambda u: u.is_staff)
def dashboard(request):
    """Dashboard for app
    Send list of domain repositories
    """
    privileges = ['admin', 'curate', 'author']
    user_repo = get_or_create_user_repo(request.user.username)
    return render_to_response('ui/dashboard.html',
                              {
                                  'enable_notifications': settings.ENABLE_NOTIFICATIONS,
                                  'privileges': privileges,
                                  'user_repo_id': str(user_repo.ident)
                              },
                              RequestContext(request))

def login_page(request):
    """Login page for app
    """
    return render_to_response('ui/login.html', {},
                              RequestContext(request))

def logout_user(request):
    """log out of the Django session"""
    logout(request)
    return HttpResponseRedirect('/')

def privacy(request):
    """Privacy policy
    """
    return render_to_response('ui/privacy.html', {},
                              RequestContext(request))

def tos(request):
    """Terms of Service for app
    """
    return render_to_response('ui/tos.html', {},
                              RequestContext(request))

templates/ui/base.html
<!DOCTYPE html>
<html lang='en' xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta charset="utf-8">
        <title>{% block title %} {% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Producer v2">
        <meta name="author" content="MIT ODL">
        <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">

        {% load i18n %}
        {% load static compress %}

        {% compress css %}
        <link rel="stylesheet" href="{{ STATIC_URL }}js/vendor/bootstrap/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="{{ STATIC_URL }}js/vendor/fontawesome/css/font-awesome.min.css">
        <link rel="stylesheet" href="{{ STATIC_URL }}js/vendor/jqueryui/themes/smoothness/jquery-ui.min.css">
        <link rel="stylesheet" href="{{ STATIC_URL }}css/producer.css">
        {% endcompress %}

        {% if enable_notifications %}
            <script data-main="{{ STATIC_URL }}js/main" src="{{ STATIC_URL }}js/vendor/requirejs/require.js"></script>
        {% else %}
            <script data-main="{{ STATIC_URL }}js/main-nn" src="{{ STATIC_URL }}js/vendor/requirejs/require.js"></script>
        {% endif %}

        {% compress css %}
        {% block header_script %} {% endblock %}
        {% endcompress %}

        {% compress js %}
        {% block header_js_script %} {% endblock %}
        {% endcompress %}
    </head>
    <body class="container-fluid has-drawer">
        {% csrf_token %}
        <div id="app-container">
            <div id="navbar-region">
                {% block navbar_content %}
                {% endblock %}
            </div>
            <div id="main-region">
                {% block main_content %}
                {% endblock %}
            </div>
            <div id="footer-region">
                <footer class="footer">
                    <div class="text-center">
                        <p>(c) 2015 Massachusetts Institute of Technology</p>
                    </div>
                    <div class="text-center">
                        <p>Application development and website support provided by the <a href="http://odl.mit.edu">MIT Office of Digital Learning (ODL)</a>.</p>
                    </div>
                </footer>
            </div>
            <div id="dialog-region">

            </div>
        </div>
    </body>
</html>

templates/ui/dashboard.html
{% extends 'ui/base.html' %}

{% block title %}Producer: Dashboard{% endblock %}

{% block header_script %}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/dashboard.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}js/vendor/bootstrap-drawer/dist/css/bootstrap-drawer.min.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}js/vendor/select2/dist/css/select2.min.css">
{% endblock %}

{% block header_js_script %}
{% endblock %}


{% block navbar_content %}
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/dashboard/">Producer</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav repository-navbar btn-group" role="group" aria-label="repository tools">
              <li class=""><button class="btn btn-lg sandbox repository-btn"><i aria-hidden="true" class="fa fa-cubes"></i> My Sandbox</button></li>
              {% if 'curate' in privileges %}
                <li class=""><button class="btn btn-lg curate-objects repository-btn"><i aria-hidden="true" class="fa fa-cogs"></i> Curate Objects</button></li>
              {% endif %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="hidden processing-spinner">
                <i aria-hidden="true" class="fa fa-spin fa-refresh">

                </i>
                <span class="sr-only">Processing...</span>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <i aria-hidden="true" class="fa fa-cogs"></i>
                  <span class="active-user" data-repo-id="{{ user_repo_id }}"> {{ user.username }}</span>
                  <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                {% if 'admin' in privileges %}
                  <li class=""><a class="add-new-domain admin-action"><i aria-hidden="true" class="fa fa-plus-circle"></i> Create New Domain</a></li>
                  <li class=""><a class="import-course admin-action"><i aria-hidden="true" class="fa fa-cloud-upload"></i> Import Course</a></li>
                {%  endif %}
                {% if 'author' in privileges %}
                  <li class=""><a class="download-from-library admin-action"><i aria-hidden="true" class="fa fa-cloud-download"></i> Export From Library</a></li>
                {% endif %}
                <li role="separator" class="divider"></li>
                <li><a href="/logout">Log out</a></li>
              </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
{% endblock %}

{% block main_content %}
    <div class="container-fluid">
        <div class="content-wrapper">
            <div id="left-canvas">

            </div>
            <div class="preview-canvas">
                <div id="notifications-region" class="pull-right">
                </div>
                <div id="preview-region">
                </div>
            </div>
        </div>
    </div>
    <div id="search-components-menu" class="drawer drawer-right dw-xs-10 dw-sm-10 dw-md-8 dw-lg-8 fold">
        <div class="container container-search drawer-contents">
          <div id="faceted-search-header" class="drawer-header">
              <div class="input-group faceted-search-header">
                  <input name="keyword-search" type="search"
                   class="form-control input-lg input-search"
                   placeholder="Search for terms in learning resource titles, descriptions or content..."/>
                <span class="facet-header-small-obj input-group-btn">
                  <button type="submit" aria-label="Submit" class="btn btn-default btn-lg execute-keyword-search">
                    <i aria-hidden="true" class="fa fa-search"></i>
                  </button>
                </span>
                <div class="domain-selector-wrapper">
                    <select class="form-control domain-selector">

                    </select>
                </div>
                <div class="facet-header-small-obj processing-spinner hidden" aria-label="Processing wait sign">
                    <div class="pull-right">
                        <i aria-hidden="true" class="fa fa-spin fa-refresh fa-2x"></i>
                        <span class="sr-only">Processing...</span>
                    </div>
                </div>
                <div class="facet-header-small-obj">
                    <button aria-label="Close" class="pull-right btn btn-primary btn-lg close-drawer">
                        <i aria-hidden="true" class="fa fa-times-circle"></i>
                        <span class="sr-only">Close Add Component Drawer</span>
                    </button>
                </div>
              </div>
          </div>
          <div class="drawer-body">
            <div class="faceted-search-container">
                <div id="faceted-search-facets" class="facets">

                </div>
                <div id="faceted-search-results-wrapper">
                    <div id="faceted-search-results">

                    </div>
                    <div id="faceted-search-pagination">

                    </div>
                </div>
            </div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="panel-group facet-region">
          </div>
        </div>
        <div class="col-md-9 search-results-region">
        </div>
    </div>
{% endblock %}

templates/ui/login.html
{% extends 'ui/base.html' %}

{% block title %}Producer: Login{% endblock %}

{% block header_script %}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/login.css">
{% endblock %}

{% block main_content %}
    <div id="login_container" class="container">
        <div class="text-center">
            <h3>Producer</h3>
        </div>
        <div class="row">
            <div id="tech_warning" class="text-center">
                <p class="text_bold red">Please note that this website is only
                    compatible with the latest versions of FF / Chrome / Safari
                    on Mac OS or FF / Chrome on Windows. It has not been tested
                    on other combinations.
                </p>
            </div>
        </div>
        <div class="row">
            <div class="text-center red">
                <p class="logintxt"> {{ state }} </p>
            </div>
            <div class="" id="login_tabs">
                <ul>
                    <li><a href='#touchstone_div'>Touchstone</a></li>
                    <li><a href='#email_div'>Login with Email</a></li>
                </ul>
                <div id="touchstone_div" class="login-box text-center">
                    <form action="{% url 'touchstone.ui:dashboard' %}" method="POST" enctype="multipart/form-data" class="form-signin">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ next }}"/>
                        <button id="login" class="btn btn-large btn-primary touchstone-login" type="submit">Touchstone Login</button>
                    </form>
                </div>
                <div id="email_div" class="login-box">
                    <form action="{% url 'ui:check' %}" method="POST" enctype="multipart/form-data" class="form-signin">
                        {% csrf_token %}
                        <label for="login_username" class="input-group">
                            <span class="input-group-addon" id="user_addon"><i class="fa fa-user"></i></span>
                            <input type="text" class="input-block-level" name="username" aria-label="username" aria-describedby="user_addon" placeholder="E-mail"/>
                        </label>
                        <label for="login_password" class="input-group">
                            <span class="input-group-addon" id="pwd_addon"><i class="fa fa-lock"></i></span>
                            <input type="password" class="input-block-level" name="password" aria-label="password" aria-describedby="pwd_addon" placeholder="Password"/>
                        </label>
                        <input type="hidden" name="next" value="{{ next }}"/>
                        <div class="text-center">
                            <button id="login_btn" class="btn btn-large btn-inverse" type="submit">Sign in</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div id="tos_pp" class="row text-center">
            <div class="text-center">
                <p>
                    Use of this site means that you agree to the
                    <a href="{% url 'ui:tos' %}" target="_blank">Terms of Service</a> and
                    <a href="{% url 'ui:privacy' %}" target="_blank">Privacy Policy</a>
                </p>
            </div>
        </div>
    </div>
{% endblock %}

templates/ui/tos.html
{% extends 'ui/base.html' %}

{% block title %}Terms of Service{% endblock %}

{% block header_script %}
{% endblock %}

{% block navbar_content %}
<h4>Producer Terms of Service</h4>
{% endblock %}

{% block main_content %}
<h2>
    Welcome to Backstage Producer.
</h2>
<p>
    You must read and agree to these Terms of Service ("TOS") and our
    <a href="{% url 'ui:privacy' %}" target="_blank">Privacy Policy</a>
    prior to registering for this site or using any portion of this site (“Site”),
    including accessing any course materials or other electronic service.
    These TOS and the Privacy Policy are agreements (the “Agreements”) between you
    and the Massachusetts Institute of Technology (“MIT”). If you do not understand
    or do not agree to be bound by the terms of the Agreements, please immediately
    exit this site.
</p>
<br />
<p>
    MIT reserves the right to modify these TOS at any time and will publish any such
    modifications online on this page. By continuing to access the Site after such
    changes have been posted, you signify your agreement to be bound by them.
    Be sure to return to this page periodically to ensure familiarity with the most
    current version of these TOS.
</p>
<h2>
    Description of ODL
</h2>
<p>
    The Office of Digital Learning (ODL) works with MIT faculty,
    staff and students to enable and promote the development and dissemination of
    innovative uses of technology in teaching and learning.
</p>
<h2>
    Rules for Online Conduct
</h2>
<p>
    You agree that you are responsible for your own use of the Site. You agree that
    you will use the Site in compliance with these TOS and all applicable local,
    state, national, and international laws, rules and regulations, including copyright
    laws and any laws regarding the transmission of technical data exported from your
    country of residence and all United States export control laws.
</p>
<br />
<p>
    As a condition of your use of the Services, you will not use the Site in any manner
    intended to damage, disable, overburden, or impair any MIT server, or the network(s)
    connected to any MIT server, or interfere with any other party's use and enjoyment
    of the Site. You may not attempt to gain unauthorized access to the Site, other accounts,
    computer systems or networks connected to any MIT server through hacking, password mining
    or any other means. You may not obtain or attempt to obtain any materials or information
    stored on the Site, its servers, or associated computers through any means not
    intentionally made available through the Site.
</p>
<br />
<p>
    The following list of items is strictly prohibited on the Site:
    <ol>
        <li>
            Content that infringes another's intellectual property, including, but not
            limited to, copyrights or trademarks.
        </li>
        <li>
            You, furthermore, agree not to scrape, or otherwise download in bulk, material
            including but not limited to on-line videos, class information, problem sets,
            assessment items, or user
            information, unless explicitly authorized. You agree to not misrepresent or
            attempt to misrepresent your identity while using the Sites (although you are
            welcome and encouraged to use an anonymous username in the forums).
        </li>
    </ol>
</p>
<h2>
    User Accounts and Authority
</h2>
<p>
    In order to participate in Site activities, you must provide an email address
    ("Email Address") and a user password ("User Password") in order to create a user
    account (“User Account”). You agree that you will never divulge or share access or
    access information to your User Account with any third party for any reason. In setting
    up your User Account, you may be prompted or required to enter additional information,
    including your name. You understand and agree that all information provided by you is
    accurate and current. You agree to maintain and update your information to keep
    it accurate and current.
</p>
<br />
<p>
    We care about the confidentiality and security of your personal information. Please
    see our <a href="{% url 'ui:privacy' %}" target="_blank">Privacy Policy</a> for
    more information about what information about you MIT collects and how MIT uses that
    information.
</p>
<h2>
    Your Right to Use Content on the Site
</h2>
<p>
    Unless indicated as being in the public domain, all content on the Site is protected by
    United States copyright. The texts, exams and other instructional materials provided
    with the courses offered on this Site are for your personal use in connection with
    those courses only.
</p>
<br />
<p>
    Certain reference documents, digital textbooks, articles and other information on the
    Site are used with the permission of third parties and use of that information is
    subject to certain rules and conditions, which will be posted along with the information.
    By using this Site you agree to abide by all such rules and conditions.
</p>
<h2>
    Use of  MIT Names, Trademarks and Service Marks
</h2>
<p>
    "MIT", "Massachusetts Institute of Technology", and its logos and seal are trademarks
    of the Massachusetts Institute of Technology. You may not use MIT’s names or logos,
    or any variations thereof, without prior written consent of MIT. You may not use the
    MIT name in any of its forms nor MIT seals or logos for promotional purposes, or in
    any way that deliberately or inadvertently claims, suggests, or in MIT's sole judgment
    gives the appearance or impression of a relationship with or endorsement by MIT.
</p>
<br />
<p>
    All Trademarks not owned by MIT that appear on the Site or on or through the services
    made available on or through the Site, if any, are the property of their respective owners.
    Nothing contained on the Site should be construed as granting, by implication, estoppel,
    or otherwise, any license or right to use any such Trademark displayed on the Site without
    the written permission of the third party that may own the applicable Trademark.
</p>
<h2>
    Digital Millennium Copyright Act
</h2>
<p>
    Copyright owners who believe their material has been infringed on the Site should
    contact MIT's designated copyright agent using the procedure outlined at the
    <a href="http://web.mit.edu/copyright/dmca-notices.html" target="_blank">MIT copyright page</a>.
</p>
<h2>
    Disclaimer of Warranty / Indemnification / Limitation of Liabilities
</h2>
<p>
    THE SITE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTY OF ANY KIND, EITHER
    EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
    MERCHANTABILITY, FITNESS FOR USE FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
    MIT does not warrant the Site will operate in an uninterrupted or error-free manner
    or that the Site is free of viruses or other harmful components. Use of information
    obtained from or through this Site is at your own risk. Your access to or download
    of information, materials, or data through the Site or any reference sites is at your
    own discretion and risk and that you will be solely responsible for any damage to your
    property (including your computer system) or loss of data that results from the download
    or use of such material or data. We may close or limit enrollment for pedagogical or
    technological reasons.
</p>
<br />
<p>
    Links to Other Sites. The Site may include hyperlinks to sites maintained or controlled
    by others. MIT is not responsible for and does not routinely screen, approve, review
    or endorse the contents of or use of any of the products or services that may be offered
    at these sites. If you decide to access linked third party web sites, you do so at your
    own risk.
</p>
<br />
<p>
    YOU AGREE THAT MIT WILL NOT BE LIABLE TO YOU FOR ANY LOSS OR DAMAGES, EITHER ACTUAL OR
    CONSEQUENTIAL, ARISING OUT OF OR RELATING TO THESE TERMS OF SERVICE, OR TO YOUR (OR ANY
    THIRD PARTY'S) USE OR INABILITY TO USE THE SITE, OR TO YOUR PLACEMENT OF CONTENT ON THE
    SITE, OR TO YOUR RELIANCE UPON INFORMATION OBTAINED FROM OR THROUGH THE SITE WHETHER
    BASED IN CONTRACT, TORT, STATUTORY OR OTHER LAW, EXCEPT ONLY IN THE CASE OF DEATH OR
    PERSONAL INJURY WHERE AND ONLY TO THE EXTENT THAT APPLICABLE LAW REQUIRES SUCH LIABILITY.
</p>
<br />
<p>
    IN PARTICULAR, MIT WILL HAVE NO LIABILTY FOR ANY CONSEQUENTIAL, INDIRECT, PUNITIVE,
    SPECIAL, EXEMPLARY OR INCIDENTAL DAMAGES, WHETHER FORESEEABLE OR UNFORESEEABLE,
    (INCLUDING, BUT NOT LIMITED TO, CLAIMS FOR DEFAMATION, ERRORS, LOSS OF DATA, OR
    INTERRUPTION IN AVAILABILITY OF DATA).
</p>
<h2>
    Indemnification
</h2>
<p>
    You agree to defend, hold harmless and indemnify MIT, and its subsidiaries, affiliates,
    officers, agents, and employees from and against any third-party claims, actions or
    demands arising out of, resulting from or in any way related to your use of the Site,
    including any liability or expense arising from any and all claims, losses, damages
    (actual and consequential), suits, judgments, litigation costs and attorneys' fees,
    of every kind and nature. In such a case, MIT will provide you with written notice of
    such claim, suit or action.
</p>
<h2>
    Miscellaneous
</h2>
<p>
    Termination Rights. You agree that MIT, in its sole discretion, may terminate your use
    of the Site or your participation in it thereof, for any reason or no reason. If you no
    longer desire to participate in the Site, you may terminate your participation therein
    upon notice to MIT.
</p>
<br />
<p>
    Entire Agreement. This Agreement constitutes the entire agreement between you and MIT
    with respect to your use of the Site, superseding any prior agreements between you and
    MIT regarding your use of the Site.
</p>
<br />
<p>
    Waiver and Severability of TOS. The failure of MIT to exercise or enforce any right or
    provision of the TOS of Site shall not constitute a waiver of such right or provision.
    If any provision of the TOS is found by a court of competent jurisdiction to be invalid,
    the parties nevertheless agree that the court should endeavor to give effect to the
    parties' intentions as reflected in the provision, and the other provisions of the TOS
    remain in full force and effect.
</p>
<br />
<p>
    Choice of Law/Forum Selection. You agree that any dispute arising out of or relating to
    these Terms or any content posted to a Site will be governed by the laws of the
    Commonwealth of Massachusetts, excluding its conflicts of law provisions.
    You further consent to the personal jurisdiction of and exclusive venue in the
    federal and state courts located in and serving Boston, Massachusetts as the legal
    forum for any such dispute.
</p>
<br />
<p>
    Effective Date: August 5, 2015
</p>
{% endblock %}